spring:
    datasource:
      driver-class-name: com.taosdata.jdbc.rs.RestfulDriver
      url: jdbc:TAOS-RS://127.0.0.1:6041/?charset=UTF-8&locale=en_US.UTF-8&timezone=UTC-8
      username: root
      password: taosdata
      type: com.zaxxer.hikari.HikariDataSource